"""Worked examples for the report-prose call (boundary 2), V4.

The examples are GENERATED BY RULE, not written by a model: for every combination of the facts the prose
writer is given (design, form of the external information, whether the release covers every predictor,
whether release terms were set aside, the selected method's family and penalty, and whether a test file
was supplied) this module writes five short sections in the report's own reference language. Because each
sentence is built from the facts of its combination, every example is correct by construction: no digit,
only references that exist in that combination, a matched design described with cases and controls, a
full release never described as partial, and no judging word. The rubric's report findings (members or
penalties misnamed, counts misused, stock phrases contradicting the facts) are the errors these examples
are meant to steer away from.

At the call, the harness picks the two combinations nearest to this run's facts and shows them before the
task. The model still writes this run's prose; the examples show the register and how the references are
used, and every draft is still checked (`check_no_digits`, `resolve`, `not_prose`) before it reaches the
report. `BREGSURV_PROSE_EXAMPLES` = on | off | <k>; on by default.
"""
from __future__ import annotations

import hashlib
import itertools
import json
import os
from functools import lru_cache
from typing import Any, Dict, List, Optional, Tuple

DEFAULT_K = 2
FEATURES = ("design", "form", "coverage", "dropped", "family", "penalty", "test")
_FORM_WORDS = {"coef": "coefficients alone", "cov": "coefficients and covariance",
               "indi": "individual-level data", "none": "no external information"}


def k_from_env() -> int:
    v = (os.environ.get("BREGSURV_PROSE_EXAMPLES") or "on").strip().lower()
    if v in ("off", "0", "no", "false"):
        return 0
    return int(v) if v.isdigit() else DEFAULT_K


def _valid(c: Dict[str, Any]) -> bool:
    d, f, fam, pen = c["design"], c["form"], c["family"], c["penalty"]
    if f == "none" and (fam != "target" or c["coverage"] != "full" or c["dropped"]):
        return False
    if f == "indi" and fam not in ("target", "indi", "released"):
        return False
    if f in ("coef", "cov") and fam == "indi":
        return False
    if fam == "released" and (pen != "none" or d == "ncc"):
        return False
    if d == "ncc" and (c["test"] or pen == "ridge"):
        return False
    if fam == "indi" and pen == "ridge":
        return False
    return True


def _refs(c: Dict[str, Any]) -> List[str]:
    r = ["n", "n_events", "p", "design", "external_form", "criteria", "nfolds", "n_candidates",
         "selected_label", "selected_borrowing", "selected_penalty", "loss_best", "loss_internal", "n_nonzero"]
    if c["design"] == "cohort":
        r.append("event_rate")
    if c["form"] != "none":
        r += ["p_covered"]
        if c["coverage"] == "partial":
            r.append("p_internal_only")
        if c["dropped"]:
            r.append("p_dropped")
        if c["design"] == "cohort":
            r.append("loss_external")
    if c["family"] not in ("target", "released"):
        r.append("eta_best")
    if c["penalty"] != "none":
        r.append("lambda_best")
    if c["test"]:
        r += ["test_n", "test_events", "test_cindex_selected", "test_loss_selected", "test_ibs_selected",
              "test_tdauc_selected"]
    return r


def _facts(c: Dict[str, Any]) -> List[str]:
    ncc = c["design"] == "ncc"
    out = ["Study design: " + ("nested case-control. The rows are cases and their matched controls; there is no "
                                "follow-up time and no censoring, and [n_events] counts the cases."
                                if ncc else "full cohort.")]
    out.append(f"External information: {_FORM_WORDS[c['form']]}.")
    if c["form"] != "none":
        out.append("The external model covers every predictor of the analysis." if c["coverage"] == "full" else
                   "The external model does not cover every predictor; the uncovered ones are estimated from the "
                   "cohort alone ([p_internal_only] of them).")
        out.append("Some terms of the external model have no column in the cohort and were set aside "
                   "([p_dropped] of them)." if c["dropped"] else
                   "Every term of the external model matched a column of the cohort.")
    fam = {"target": "the cohort alone", "kl": "Kullback-Leibler borrowing",
           "space": "coefficient-space borrowing", "released": "the external model unchanged",
           "indi": "individual-level borrowing"}[c["family"]]
    pen = {"none": "", "ridge": " with a ridge penalty", "lasso": " with a lasso penalty"}[c["penalty"]]
    out.append(f"Selected method: {fam}{pen}. It was selected because it has the lowest cross-validated loss of "
               "the admissible set; nothing else was weighed.")
    out.append("The analyst supplied a separate test file; the selected model's measures on it are the test_ "
               "references. The selection did not use it." if c["test"] else
               "No test file was supplied; the cross-validated loss is the only performance quantity in this report.")
    return out


def _sections(c: Dict[str, Any]) -> Dict[str, str]:
    ncc, form, fam, pen = c["design"] == "ncc", c["form"], c["family"], c["penalty"]
    if ncc:
        data = ("The analysis uses [n] subjects in matched sets, [n_events] of them cases and the others their "
                "matched controls, with [p] predictors.")
    else:
        data = ("The cohort has [n] subjects, [n_events] of whom had the event ([event_rate]), "
                "with [p] predictors.")
    data += (" No external information was supplied." if form == "none" else
             " The external information arrived as [external_form].")
    if form == "none":
        link = "With no external information there is nothing to link; every coefficient comes from the cohort alone."
    elif form == "indi":
        link = ("The external cohort's records carry the predictors of the analysis, [p_covered] of the [p], "
                "so both cohorts enter one likelihood.")
    elif c["coverage"] == "full":
        link = "The external model has a coefficient for every predictor of the analysis, [p_covered] of [p]."
    else:
        link = ("The external model covers [p_covered] of the [p] predictors; the other [p_internal_only] are "
                "estimated from the cohort alone.")
    if form != "none" and c["dropped"]:
        link += " [p_dropped] terms of the external model have no column in the cohort and were set aside."
    if form == "none":
        cand = ("The admissible set has [n_candidates] members, all fitted to the cohort alone, because no "
                "external information was supplied.")
    else:
        cand = ("The admissible set has [n_candidates] members, fixed by the study design, [design], and the form "
                "of the external information, [external_form]. It holds the fit to the cohort alone"
                + ("" if ncc else " and the external model used unchanged")
                + " beside the methods that borrow.")
    comp = ("Every member was scored by [criteria] on one partition into [nfolds] folds. The selected method "
            "reached [loss_best], against [loss_internal] for the fit to the cohort alone"
            + (" and [loss_external] for the external model used unchanged" if (form != "none" and not ncc) else "")
            + ".")
    if fam == "target":
        sel = ("The selected method is [selected_label], which uses the cohort alone"
               + (" with [selected_penalty] at weight [lambda_best], keeping [n_nonzero] non-zero coefficients."
                  if pen != "none" else ", so the external information did not change its coefficients."))
    elif fam == "released":
        sel = ("The selected method is [selected_label]: the external model is used as published, and no "
               "coefficient was re-estimated from the cohort.")
    else:
        sel = ("The selected method is [selected_label]. It uses [selected_borrowing] with borrowing weight "
               "[eta_best]"
               + (", and [selected_penalty] at weight [lambda_best], keeping [n_nonzero] non-zero coefficients."
                  if pen != "none" else "; each coefficient is pulled toward the external information by that weight."))
    if c["test"]:
        sel += (" On the test file of [test_n] subjects with [test_events] events, its concordance index is "
                "[test_cindex_selected] and its integrated Brier score [test_ibs_selected].")
    return {"data": data, "linkage": link, "candidates": cand, "comparison": comp, "selected": sel}


@lru_cache(maxsize=1)
def bank() -> List[Dict[str, Any]]:
    vals = {"design": ("cohort", "ncc"), "form": ("coef", "cov", "indi", "none"), "coverage": ("full", "partial"),
            "dropped": (0, 1), "family": ("target", "kl", "space", "released", "indi"),
            "penalty": ("none", "ridge", "lasso"), "test": (0, 1)}
    out = []
    for combo in itertools.product(*(vals[f] for f in FEATURES)):
        c = dict(zip(FEATURES, combo))
        if not _valid(c):
            continue
        cid = "P" + "-".join(str(c[f]) for f in FEATURES)
        out.append({"id": cid, "features": c, "facts": _facts(c), "references": _refs(c),
                    "sections": _sections(c)})
    return out


def bank_sha256() -> str:
    return hashlib.sha256(json.dumps(bank(), sort_keys=True).encode()).hexdigest()[:16]


def features_of(res: Dict[str, Any], refs: Dict[str, Any]) -> Dict[str, Any]:
    f = res["facts"]; key = (res.get("selected") or {}).get("key", "")
    form = (f.get("external_form") or "none").lower()
    form = ("none" if form in ("none", "no external information") else "indi" if "individual" in form
            else "cov" if "covariance" in form else "coef")
    base = key[:-5] if key.endswith("_ties") else key
    fam = ("released" if base.startswith("external") else "target" if base.startswith("internal")
           else "kl" if base.startswith(("kl", "discretekl")) else "indi" if base.startswith("indi") else "space")
    pen = "lasso" if base.endswith("_lasso") else "ridge" if base.endswith("_ridge") else "none"
    return {"design": "ncc" if "case-control" in str(f.get("design")) else "cohort", "form": form,
            "coverage": "partial" if refs.get("p_internal_only") else "full",
            "dropped": 1 if refs.get("p_dropped") else 0, "family": fam, "penalty": pen,
            "test": 1 if res.get("test_data") else 0}


def nearest(feat: Dict[str, Any], k: int) -> List[Dict[str, Any]]:
    w = {"design": 3, "form": 3, "family": 3, "penalty": 2, "coverage": 2, "dropped": 1, "test": 1}
    scored = sorted(bank(), key=lambda e: (-sum(w[f] for f in FEATURES if e["features"][f] == feat.get(f)), e["id"]))
    return scored[:k]


def render(examples: List[Dict[str, Any]]) -> str:
    if not examples:
        return ""
    parts = ["Worked examples for other analyses (their facts differ from this one's; write only what THIS "
             "analysis's facts say):"]
    for j, e in enumerate(examples, 1):
        parts.append(f"Example {j}\nFacts:\n" + "\n".join("  " + s for s in e["facts"])
                     + "\nReferences available: " + ", ".join(f"[{r}]" for r in e["references"])
                     + "\nProse:\n" + json.dumps(e["sections"], ensure_ascii=False))
    return "\n\n".join(parts) + "\n\nNow the analysis to write.\n\n"


def for_run(res: Dict[str, Any], refs: Dict[str, Any]):
    k = k_from_env()
    if not k:
        return "", None
    ex = nearest(features_of(res, refs), k)
    return render(ex), {"k": k, "ids": [e["id"] for e in ex], "bank_sha256": bank_sha256(),
                        "bank_items": len(bank())}
