"""Retrieved worked examples for reading an external file (M5 `external_roles`), V4.

The bank (`examples/release_bank.json`, built by `eval/make_release_bank.py`) holds file layouts rendered as
the model is shown them -- table names, column names, types and ranges, never a row -- each with its correct
assignment, generated by rule so the reading is right by construction. At the call the harness retrieves the
k layouts most similar to the uploaded file's (BM25 over the rendered text, fused with a dense ranking and
reranked, `retrieval.py`) and shows them before the file. The assignment is still checked by
`external.check_assignment` and `canonicalise` against the file itself; an example can only shape the reading.
`BREGSURV_RELEASE_EXAMPLES` = on | off | <k>; on by default (k = 3) when the bank exists.
"""
from __future__ import annotations

import hashlib
import json
import math
import os
from collections import Counter
from functools import lru_cache
from pathlib import Path
from typing import Any, Dict, List, Optional

from . import fewshot, retrieval

BANK_PATH = Path(os.environ["BREGSURV_RELEASE_BANK"]) if os.environ.get("BREGSURV_RELEASE_BANK") else Path(__file__).resolve().parent / "examples" / "release_bank.json"
DEFAULT_K = 3
_K1, _B = 1.5, 0.75


def k_from_env() -> int:
    v = (os.environ.get("BREGSURV_RELEASE_EXAMPLES") or "on").strip().lower()
    if v in ("off", "0", "no", "false"):
        return 0
    return int(v) if v.isdigit() else DEFAULT_K


class Bank:
    def __init__(self, path: Path = BANK_PATH):
        raw = path.read_bytes()
        self.path = path
        self.sha256 = hashlib.sha256(raw).hexdigest()[:16]
        self.items: List[Dict[str, Any]] = json.loads(raw)["items"]
        self.masked = [it["summary"] for it in self.items]
        self.docs = [fewshot.tokens(t) for t in self.masked]
        self.avgdl = sum(len(d) for d in self.docs) / max(1, len(self.docs))
        df: Counter = Counter()
        for d in self.docs:
            df.update(set(d))
        n = len(self.docs)
        self.idf = {t: math.log(1 + (n - c + 0.5) / (c + 0.5)) for t, c in df.items()}
        self.tf = [Counter(d) for d in self.docs]
        self.last_retrieval: Dict[str, Any] = {}

    def score(self, q: List[str], i: int) -> float:
        tf, dl, s = self.tf[i], len(self.docs[i]), 0.0
        for t in q:
            f = tf.get(t, 0)
            if f:
                s += self.idf.get(t, 0.0) * f * (_K1 + 1) / (f + _K1 * (1 - _B + _B * dl / self.avgdl))
        return s

    def retrieve(self, summary: str, k: int = DEFAULT_K) -> List[Dict[str, Any]]:
        if k <= 0 or not self.items:
            return []
        q = fewshot.tokens(summary)
        cand = list(range(len(self.items)))
        bm = {i: self.score(q, i) for i in cand}
        order, self.last_retrieval = retrieval.rank(self.path, self.masked, summary, bm, cand)
        out, kinds = [], set()
        for i in order:            # one example per layout kind, so the k examples differ
            it = self.items[i]
            if it["kind"] in kinds:
                continue
            kinds.add(it["kind"])
            out.append(dict(it, _score=round(bm.get(i, 0.0), 4)))
            if len(out) >= k:
                break
        return out


@lru_cache(maxsize=1)
def bank() -> Optional[Bank]:
    return Bank() if BANK_PATH.exists() else None


def render(examples: List[Dict[str, Any]]) -> str:
    if not examples:
        return ""
    parts = ["Worked examples of reading other files (different variables; nothing in them is in this file):"]
    for j, it in enumerate(examples, 1):
        parts.append(f"Example {j}\nTables in that file:\n\n{it['summary']}\n\nCorrect reading:\n"
                     f"{json.dumps(it['answer'], ensure_ascii=False)}")
    return "\n\n".join(parts) + "\n\nNow read this file.\n\n"


def for_tables(summary: str):
    """(prompt prefix, record) for one external_roles call; ("", None) when off or the bank is absent."""
    k = k_from_env()
    b = bank()
    if not k or b is None:
        return "", None
    try:
        ex = b.retrieve(summary, k)
    except Exception as exc:  # noqa: BLE001 -- examples never stop a reading
        return "", {"k": k, "error": f"{type(exc).__name__}: {exc}"}
    return render(ex), {"k": k, "ids": [e["id"] for e in ex], "kinds": [e["kind"] for e in ex],
                        "bank_sha256": b.sha256, "bank_items": len(b.items),
                        "retrieval": dict(b.last_retrieval)}
